services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    restart: unless-stopped

    command:
      - start

    ports:
      - "8443:8443"

    volumes:
      - /etc/ssl/keycloak:/etc/x509/https:ro

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER_KEYCLOAK}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}

      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}

      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key

      KC_HEALTH_ENABLED: "true"

    depends_on:
      keycloak_postgres:
        condition: service_healthy

    networks:
      - banking-network


  keycloak-postgres:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER_KEYCLOAK}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - banking-network

volumes:
  postgres_data: