spring:
  application:
    name: ms-notification

  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2
          max-interval: 5m

  mail:
    host: ${MAIL_HOSTNAME}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance-id: ${spring.application.name} ${random.int}
    prefer-ip-address: true