spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-customer
              uri: lb://MS-CUSTOMER
              predicates:
                - Path=/ms-customer/**
              filters:
                - StripPrefix=1

            - id: ms-auth
              uri: lb://MS-AUTH
              predicates:
                  - Path=/ms-auth/**
              filters:
                - StripPrefix=1
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    registry-fetch-interval-seconds: 5 # Gateway consulta o Eureka a cada 5 segundos, em vez de esperar 30.

  instance:
    instance-id: ${spring.application.name} ${random.int}
    prefer-ip-address: true