spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-customer
              uri: lb://MS-CUSTOMER
              predicates:
                - Path=/ms-customer/**
              filters:
                - StripPrefix=1

            - id: ms-auth
              uri: lb://MS-AUTH
              predicates:
                  - Path=/ms-auth/**
              filters:
                - StripPrefix=1

            - id: ms-account
              uri: lb://MS-ACCOUNT
              predicates:
                - Path=/ms-account/**
              filters:
                - StripPrefix=1

            - id: ms-ai
              uri: lb://MS-AI
              predicates:
                - Path=/ms-ai/**
              filters:
                - StripPrefix=1
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    registry-fetch-interval-seconds: 5 # Gateway consulta o Eureka a cada 5 segundos, em vez de esperar 30.

  instance:
    instance-id: ${spring.application.name} ${random.int}
    prefer-ip-address: true