spring:
  application:
    name: ms-customer

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking

  profiles:
    active: dev

  rabbitmq:
    host: ${RABBITMQ_HOSTNAME}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2
          max-interval: 5m

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    registry-fetch-interval-seconds: 5 # Gateway consulta o Eureka a cada 5 segundos, em vez de esperar 30.

  instance:
    instance-id: ${spring.application.name} ${random.int}
    prefer-ip-address: true # eureka registra usando do endereço IP da máquina