spring:
  application:
    name: ms-card

  profiles:
    active: dev

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka

  instances:
    instance-id: ${spring.application.name}/${random.int}